#!/usr/bin/env uv run
# /// script
# dependencies = [
#     "mini3di",
# ]
# ///
"""
scripts/dump_weights.py

Extracts weights, biases, and centroids from Python mini3di (encoder_weights_3di.kerasify and Encoder._CENTROIDS)
and outputs static Rust code to src/weights.rs.
"""

import struct
import subprocess
import sys
from pathlib import Path

# Absolute paths
REPO_DIR = Path(__file__).resolve().parent.parent
OUTPUT_RUST_PATH = REPO_DIR / "src" / "weights.rs"

# Fallback/Default centroids from mini3di.encoder.Encoder._CENTROIDS
DEFAULT_CENTROIDS = [
    [-1.0729, -0.3600],
    [-0.1356, -1.8914],
    [0.4948, -0.4205],
    [-0.9874, 0.8128],
    [-1.6621, -0.4259],
    [2.1394, 0.0486],
    [1.5558, -0.1503],
    [2.9179, 1.1437],
    [-2.8814, 0.9956],
    [-1.1400, -2.0068],
    [3.2025, 1.7356],
    [1.7769, -1.3037],
    [0.6901, -1.2554],
    [-1.1061, -1.3397],
    [2.1495, -0.8030],
    [2.3060, -1.4988],
    [2.5522, 0.6046],
    [0.7786, -2.1660],
    [-2.3030, 0.3813],
    [1.0290, 0.8772],
]


def load_layers_using_unkerasify(kerasify_path: Path | None = None):
    """Attempt loading via mini3di package."""
    try:
        import mini3di
        from mini3di import _unkerasify
        from mini3di.encoder import Encoder

        if kerasify_path is None or not kerasify_path.exists():
            pkg_dir = Path(mini3di.__file__).parent
            kerasify_path = pkg_dir / "encoder_weights_3di.kerasify"

        with open(kerasify_path, "rb") as f:
            layers = _unkerasify.load(f)
        centroids = Encoder._CENTROIDS.tolist()
        return layers, centroids
    except Exception as e:  # noqa: BLE001
        print(
            f"Notice: Could not load via mini3di module ({e}), falling back to struct parser."
        )
        return None, None


def parse_kerasify_binary(kerasify_path: Path):
    """Parse binary .kerasify file directly using struct module."""
    with open(kerasify_path, "rb") as f:
        (n_layers,) = struct.unpack("I", f.read(4))
        layers = []
        for _ in range(n_layers):
            (layer_type,) = struct.unpack("I", f.read(4))
            if layer_type != 1:  # DENSE
                raise ValueError(f"Unsupported layer type: {layer_type}")
            (w0,) = struct.unpack("I", f.read(4))
            (w1,) = struct.unpack("I", f.read(4))
            (b0,) = struct.unpack("I", f.read(4))

            w_count = w0 * w1
            w_bytes = f.read(w_count * 4)
            weights_flat = list(struct.unpack(f"={w_count}f", w_bytes))
            # Reshape (w0, w1)
            weights = [weights_flat[i * w1 : (i + 1) * w1] for i in range(w0)]

            b_bytes = f.read(b0 * 4)
            biases = list(struct.unpack(f"={b0}f", b_bytes))

            (activation,) = struct.unpack("I", f.read(4))

            # Simple layer representation wrapper
            class DenseData:
                def __init__(self, w, b, act):
                    self.weights = w
                    self.biases = b
                    self.activation = act

            layers.append(DenseData(weights, biases, activation))
        return layers


def format_f32(val: float) -> str:
    """Format float32 to Rust literal float string preserving precision."""
    # Convert numpy scalar to float if needed
    val = float(val)
    formatted = f"{val:.9g}"
    if "." not in formatted and "e" not in formatted and "E" not in formatted:
        formatted += ".0"
    return formatted


def format_1d_array(arr) -> str:
    elems = [format_f32(x) for x in arr]
    return "[\n    " + ", ".join(elems) + ",\n]"


def format_2d_array(arr) -> str:
    rows = []
    for row in arr:
        elems = [format_f32(x) for x in row]
        rows.append("    [" + ", ".join(elems) + "]")
    return "[\n" + ",\n".join(rows) + ",\n]"


def generate_rust_code(layers, centroids) -> str:
    # Handle layers if numpy arrays or python lists
    l1_w = format_2d_array(layers[0].weights)
    l1_b = format_1d_array(layers[0].biases)
    l2_w = format_2d_array(layers[1].weights)
    l2_b = format_1d_array(layers[1].biases)
    l3_w = format_2d_array(layers[2].weights)
    l3_b = format_1d_array(layers[2].biases)
    cent = format_2d_array(centroids)

    return f"""// Auto-generated by scripts/dump_weights.py. DO NOT EDIT DIRECTLY.
#![allow(clippy::all)]
#![allow(dead_code)]

//! Static VQ-VAE neural network weights, biases, and cluster centroids
//! for 3Di structural alphabet encoding.

/// Layer 1 Dense weights (10 inputs -> 10 outputs).
pub const LAYER1_WEIGHTS: [[f32; 10]; 10] = {l1_w};

/// Layer 1 Dense biases (10 outputs).
pub const LAYER1_BIASES: [f32; 10] = {l1_b};

/// Layer 2 Dense weights (10 inputs -> 10 outputs).
pub const LAYER2_WEIGHTS: [[f32; 10]; 10] = {l2_w};

/// Layer 2 Dense biases (10 outputs).
pub const LAYER2_BIASES: [f32; 10] = {l2_b};

/// Layer 3 Dense weights (10 inputs -> 2 outputs).
pub const LAYER3_WEIGHTS: [[f32; 2]; 10] = {l3_w};

/// Layer 3 Dense biases (2 outputs).
pub const LAYER3_BIASES: [f32; 2] = {l3_b};

/// 20 2D centroids for VQ-VAE nearest-neighbor quantization.
pub const CENTROIDS: [[f32; 2]; 20] = {cent};
"""


def main():
    kerasify_path = None
    output_path = OUTPUT_RUST_PATH

    if len(sys.argv) > 1:
        kerasify_path = Path(sys.argv[1])
    if len(sys.argv) > 2:
        output_path = Path(sys.argv[2])

    print(f"Loading weights (kerasify path override: {kerasify_path or 'auto'})...")
    layers, centroids = load_layers_using_unkerasify(kerasify_path)

    if layers is None:
        if kerasify_path is not None and kerasify_path.exists():
            print(f"Parsing binary format directly with struct from {kerasify_path}...")
            layers = parse_kerasify_binary(kerasify_path)
            centroids = DEFAULT_CENTROIDS
        else:
            raise RuntimeError(
                "Failed to load mini3di layers and no valid custom kerasify file path provided."
            )

    code = generate_rust_code(layers, centroids)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(code)
    print(f"Successfully generated static weights at {output_path}")
    subprocess.run(["cargo", "fmt", "--", str(output_path)], check=False)


if __name__ == "__main__":
    main()
